CREATE TABLE IF NOT EXISTS `registrations` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name_child` text COLLATE utf8_unicode_ci NOT NULL,
  `birthdate` text COLLATE utf8_unicode_ci NOT NULL,
  `allergy` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `medication` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `swimmingbadge` int COLLATE utf8_unicode_ci DEFAULT 0,
  `sailingexperience` int COLLATE utf8_unicode_ci NOT NULL,
  `clothingsize` int COLLATE utf8_unicode_ci NOT NULL,
  `lifejacket` int COLLATE utf8_unicode_ci DEFAULT 0,
  `firstname_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `lastname_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `email_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `mobilenumber_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `phonenumber_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `plz_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `town_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `street_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `housenumber_parent1` text COLLATE utf8_unicode_ci NOT NULL,
  `firstname_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `lastname_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `email_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `mobilenumber_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `phonenumber_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `plz_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `town_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `street_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `housenumber_parent2` text COLLATE utf8_unicode_ci NOT NULL,
  `other` text COLLATE utf8_unicode_ci NOT NULL,
  `correctinformation` int COLLATE utf8_unicode_ci NOT NULL,
  `disclaimer` int COLLATE utf8_unicode_ci NOT NULL,
  `coronasymptoms` int COLLATE utf8_unicode_ci NOT NULL,
  `whatsapp` int COLLATE utf8_unicode_ci DEFAULT 0,
  `publishphotos` int COLLATE utf8_unicode_ci DEFAULT 0,
  `user_ip` text COLLATE utf8_unicode_ci NOT NULL,
  `user_useragent` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `accepted` int COLLATE utf8_unicode_ci DEFAULT 0,
  `amount_payed` text COLLATE utf8_unicode_ci DEFAULT '0,00 €',
  `boat_name` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE (`name_child`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
